<?php
use Magento\Framework\Escaper;

/**
 * @var $block \DUna\Payments\Block\Checkout
 * @var Escaper $escaper
 */

$env = $block->getEnv();
$apiKey = $block->getApiKey();
$btnLabel = $escaper->escapeHtml(__('Checkout'));
?>

<div id="duna-checkout" data-bind="scope:'duna'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#duna-checkout": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "duna": {
                        "component": "DUna_Payments/js/checkout-widget",
                        "env": "<?= $env ?>",
                        "apiKey": "<?= $apiKey ?>",
                        "btnLabel": "<?= $btnLabel ?>"
                    }
                }
            }
        }
    }
    </script>
    <script>
        require(['jquery' ,'Magento_Customer/js/customer-data'], function ($,customerData) {
            $('#block-summary').on('change', function() {
                setTimeout(function() {
                    var data = window.localStorage.getItem('mage-cache-storage');
                    var parsedData = JSON.parse(data);
                    var shippingMethodCode = parsedData['cart-data'].shippingMethodCode;

                    $.ajax({
                        url: '/duna/set/shippingmethoddata',
                        type: 'post',
                        data: {
                            shippingMethodCode: shippingMethodCode
                        },
                        success: function(response) {
                           // console.log('Save data in session');
                        }
                    });
                }, 1000);
            });
        });
    </script>
</div>
