version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DUNA_ACTION_TOKEN}}

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "UTC"
    target-branch: develop
    registries: "*"
    commit-message:
      prefix: "[composer] security"

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "UTC"
    target-branch: develop
    registries: "*"
    commit-message:
      prefix: "[docker] security"

  - package-ecosystem: "gitsubmodule"
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "UTC"
    target-branch: develop
    registries: "*"
    commit-message:
      prefix: "[gitsubmodule] security"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "UTC"
    target-branch: develop
    registries: "*"
    commit-message:
      prefix: "[github-actions] security"
